// Code that generates the random lorem ipsum text

// Create a new object called loremIpsum by invoking the GenerateNewText constructor function
const loremIpsum = new GenerateNewText();

// Constructor function that creates an object with the paragraph property
function GenerateNewText() {
    // Add property to the object
    this.sentences = [
        "Monica decides to give Chandler his anniversary present a day early: tickets to Las Vegas; Phoebe insists everyone goes, to make up for her missing London (she was pregnant with triplets at the time). Ross and Rachel have previous engagements but decide to follow the next day.On the plane, as Phoebe goes to the restroom, Chandler realizes he forgot the anniversary present, but Monica immediately forgives him. Chandler replies, This is the worst anniversary ever the minute Phoebe returns, making Phoebe believe that Monica told him about Richard, saying, So you told him about the Richard thing.",
        "In the next scene, Rachel asks Monica if she would like to go and see a movie with her and Phoebe. Monica tells her that she had plans to do laundry but she was obviously lying. In response, Rachel gives her a large bag of laundry to do, and Phoebe gives her a sack of quarters for the machines at the laundromat, so Monica and Chandler's plans are ruined.As Rachel and Phoebe leave, Phoebe tells Chandler that she will miss him in a seductive voice, and pinches his butt. Monica then realizes that Phoebe truly isn't attracted to Chandler, and that she has actually discovered that they are sleeping together.",
        "Ross deals with finding out about Rachel and Joey's relationship almost as well as when he found out about Monica and Chandler - that is, not well at all - but out of loyalty and embarrassment, maintains that he is totally 'fine'. The only problem is that everyone can see through his ruse: the word “fine” keeps coming out all high-pitched and squeaky. In an attempt to prove that he is completely 'fine' with the new relationship, Ross invites Rachel and Joey to a dinner party with him and Charlie. Before dinner, however, Ross is obviously tense and anxious, almost on the verge of tears. Joey suggests a drink to calm Ross' nerves, Ross quickly goes overboard with Joey.",
        "In the teaser, Chandler and Monica cuddle while cooperating on a crossword puzzle, which Joey finds cute. That night, however, he dreams that he was doing the crossword puzzle with Monica, leading him to wonder if he finds her attractive. This is exacerbated when, at Central Perk the next morning, Monica is found wearing his sweatshirt as opposed to Chandler's, and later when Monica asks him to taste her cooking, leading to him confessing about his dreams. A bit of honest discussion between the three of them reveals that Joey is not really attracted to Monica, but rather to the intimacy and friendship she shares with Chandler. The two explain that this is because they were friends first before they started dating.",
        "While digging beneath a Central Perk chair cushion for spare change, Phoebe uncovers a policeman's badge. Though she promises to return it, she finds using it far more entertaining, exploiting her new-found power to force a smoking bystander to apologize to a tree on which she snubbed out a cigarette. When she begins threatening her friends with arrest, she realizes she has gone too far, but before she can return it, she tries to force an illegally-parked man to move his car. He turns out to be a policeman as well, and is unimpressed when she claims to be an undercover cop from the 15th district of Manhattan. This fellow, Gary, turns out to be the owner of the badge, but when he arrives at Monica's apartment to arrest her, he asks her out on a date instead.",
        "Ross buys a new couch and decides to carry it up to his apartment instead of paying a delivery fee since delivery fees was too much.Rachel recruits Chandler to help her and Ross do the heavy lifting. As each one grabs a part of the couch, they ascend the stairs and attempt to navigate the first curve into the stairwell.“Turn! Turn! Turn!” Ross shouts. “Here we go! Pivot! PIVOT! PI-VOT!” he yells, emphasizing the “vot” like it rhymes with “hot” or “lot,” and finally cascading into an embarrassing “PI-VAT.” Naturally, Rachel and Chandler get frustrated from the yelling and whatever they’re trying to pull off not working, which ends in the couch being stuck between the walls.",
        "The gang observes that \"Ugly Naked Guy\", who lives across the street from them, is moving out. Ross, who has lived in Joey and Chandler's apartment since his botched wedding with Emily, wonders if he should try to get Ugly Naked Guy's apartment. He, Rachel and Phoebe visit it, and Ross is enthralled, but while he goes for an application, the girls see Chandler and Monica having intercourse in Monica's apartment. Though initially shocked, Phoebe calms down after Joey and Rachel reveal the two have been together since hooking up at Ross's wedding. Joey, who has been keeping the secret for several months, is relieved that almost everyone knows. However, Rachel and Phoebe want revenge, and decide to mess with the duo by having Phoebe pretend to be attracted to Chandler. Chandler later informs a skeptical Monica that Phoebe was flirting with him.",
        "Monica overhears Phoebe flirting with Chandler, and realises he was telling the truth. However, she also realises that Phoebe knows about their relationship and is just trying to mess with them. They confront Joey, who inadvertently reveals Rachel knows as well. Chandler and Monica decide to turn the tables by having Chandler reciprocate Phoebe's advances; to which Rachel and Phoebe realize what the couple are doing and proceed to up the stakes. The game of chicken between the two culminates with Chandler and Phoebe going on a tense date in Chandler and Joey's apartment while Monica hides in the bathroom and Rachel and Joey eavesdrop in the hallway. After Phoebe and Chandler share an awkward kiss, Chandler finally breaks down and reveals he is in love with Monica. Monica reveals that she is also in love with Chandler.",
        "Ross continues to seek forgiveness from Rachel for the list, but she tells him that they together as a couple will never happen. Phoebe thinks otherwise, however, calling Ross and Rachel lobsters. When she receives blank looks, she explains: \"It's a known fact that lobsters fall in love and mate for life. You can actually see old lobster couples walking around their tank, holding claws.\" Monica returns from a bad interview at a restaurant where the chef tries to come onto her. She mulls over her options now that her funds are dwindling, but is anxious of whether to borrow from her parents. Jack and Judy Geller bring boxes of Monica's possessions to her apartment because they are turning her room into a gym. Monica eventually tells them that she was fired from her job. However, Jack reminds Monica that 10% of her paycheck goes to her bank account and encourages her to use her savings, assuring them that they will be there to lend money to her whenever she needs it. Ross also lends her money to help pay for her rent.",
        "While looking through the box of possessions, Monica finds a video of her and Rachel getting ready for their senior prom. The friends decide to watch the video although Ross objects to everyone seeing the tape. The video reveals that Monica was previously obese, and that Rachel had a large nose. Rachel seems to be stood up by her prom date, Chip Matthews, so after some persuading from Judy, Ross plans to take her to prom instead. He dresses up in his father's tuxedo, and finds a makeshift flower bouquet, but Rachel's date shows up before she learns of Ross' plans. The video ends with Ross looking disappointed and rejected. Rachel, touched by Ross' gesture, gets up and passionately kisses Ross, forgiving him for what happened between them. The episode ends with Phoebe exclaiming \"See, he's her lobster!\"",
        "Ross arrives at Monica's apartment to discover Joey, Chandler and Rachel are not yet dressed for a function that evening. Joey sits on the chair Chandler was recently sitting in causing an argument between them, resulting in hummus staining Phoebe's dress. Meanwhile, Ross yells at Rachel causing her to say she will not go to the function. Chandler hides Joey's underwear, so Joey puts on all Chandler's clothes he can find. \"Okay, buddy-boy. Here it is. You hide my clothes, I'm wearing everything you own. Look at me, I am Chandler. Could I be wearing anymore clothes? Maybe if I wasn't going commando!\" Joey says.",
        "Ross's complaint that his divorce and eviction means he is having the worst Thanksgiving ever prompts the others to tell their stories of bad holidays that they had gone by before. Chandler reminds everyone of the Thanksgiving where his parents told him they were getting a divorce. Phoebe then tells of a worse one from a past life where she lost an arm, though Ross disqualifies her story, limiting the tales to true lives. Rachel says she knows Monica's worst Thanksgiving, but Phoebe interrupts with a story about the Thanksgiving when Joey got a turkey stuck on his head. Joey intended to freak Chandler out with the turkey, so Phoebe, and later Monica, after she comes home, attempt to pull the turkey out.",
        "Back in 1988, Ross and Chandler (dressed like members of Miami Vice) arrive for dinner to find Monica has slimmed down, and Chandler now finds her attractive. Monica tells Rachel that she wants to humiliate Chandler for calling her fat before, so Rachel suggests tricking him into taking off his clothes. Based on Rachel's suggestion that she act like everything around her turns her on, Monica tries to seduce Chandler by rubbing various objects, including a knife, against herself. She accidentally drops the knife and severs Chandler's toe,. He is rushed to hospital to have it reattached but, in the commotion, Monica unknowingly mixed up the digit with a small piece of carrot. In the present, Chandler becomes upset after learning that he had lost his toe because he called Monica fat, and angrily leaves. When Monica comes by his apartment seeking his forgiveness by putting a turkey on her head, puts a fez hat and large glasses on it, and dances for him, making him inadvertently tell her he loves her for the first time in their relationship. And the turkey on Monica's head freaks Joey out.",
        "After ending up at the wrong airport and calling Monica to verify their information, Ross and Phoebe race to the right airport. Afraid they are not going to make it in time to catch Rachel (who is actually already on the plane), Phoebe calls Rachel, telling her there's something wrong with the plane's \"left phalange\". The guy sitting next to Rachel freaks out and alarms the rest of the passengers, making everyone get off. This diversion is perfect for Ross, who catches Rachel just before she takes off again (also thanks to Phoebe's screaming, which makes Rachel turn around at the gates). Ross confesses his love for Rachel and says he wants to be with her, but it's too much for Rachel to take at the moment and all she can say to Ross is \"I'm sorry, I'm sorry. I'm so sorry\" and passes through the gates again.",
        'As a house-warming gift, Joey has bought Chandler and Monica a new chick and duck, Chick Jr. and Duck Jr. However, when he tries to show them to Monica and Chandler, he cannot find them in his apartment. When he tells them, Chandler helps him search for the birds while Monica finishes packing. The two realize that Chick Jr. and Duck Jr are stuck inside the foosball table, which Joey and Chandler don\'t want to break.  Chandler and Joey, who are emotionally attached to the foosball table, find they are unable to break it open, but Monica does gleefully with a crowbar and mallet. "See you girls later.", she said while leaving. After they retrieve the birds, Chandler suggests Joey keep them, and the two reaffirm their friendship with a long, tense hug.',
        "Because Monica had work on Valentine's Day, Chandler tells the group that the two of them are celebrating tonight. After Joey suggests that they each book a day at one of those romantic spas, Chandler says that he and Monica have decided to make each other home made presents this year, however Chandler has forgotten to make one for Monica. Phoebe offers to give him a sock-bunny for a present but he declines. At his scours their bedroom for a present, he finds a mix-tape at the bottom of the closet at the last second and gives that to Monica. In return, he receives one of Phoebe's sock-bunnies from Monica, who had obviously also forgotten. Feeling guilty over giving such a lousy gift while Chandler actually seemingly put effort into his, Monica promises to make all Chandler's wishes come true in the kitchen and in the bedroom. The following day, Monica becomes the perfect girlfriend as she showers Chandler with love, attention and gifts. However, that night Monica decides to listen to Chandler's mix tape, and the two share a romantic moment dancing... until Janice's voice appears on the tape, her having given it to Chandler on one of his birthdays. Monica is furious and Chandler begs for forgiveness.",
        "Phoebe and Rachel take self-defense classes that have them bragging about how they can kick anyone's ass. Ross tells them that after years of studying karate he has learned that self-defense is useless without \"Unagi\", a state of total awareness. Rachel and Phoebe tell him that Unagi is a sushi and that there's no such thing, with Chandler later telling him the same thing. After Ross jump scares them, the two return the favor in his apartment. This causes Ross to sneak into Phoebe's apartment but he fails to hide successfully, as the girls notice him as they enter their home. They easily subdue him, which causes Ross to go to their instructor to ask how to fight them off, but he doesn't explain himself clearly, failing to explain that Rachel and Phoebe attacked him first, causing him to come across as a man who enjoys attacking women, especially his ex-wife. The instructor of course, disagrees to help Ross.",
        "Phoebe scares Rachel from telling the father when she remarks how her confession will change the father's life completely, something which Rachel doesn't want as she believes she's ready to raise her child by herself. Rachel is still intent not to tell who the father is, but when Joey suspects something, Phoebe sticks with her story from the wedding that she is pregnant. Joey is incredibly happy for Phoebe but equally sad that she'll be raising her kid without a father, so he proposes to fix things - by proposing to Phoebe, who accepts. Monica tells Joey that it's Rachel who's pregnant, and how she and Phoebe know about this but don't know anything about the father. This sparks something in Joey's mind, who at his apartment, finds a red sweater which he has had for a month and believes is the father's. Phoebe drags Rachel to Central Perk, where she has arranged for the father to be. Rachel, still unsure about telling the father, enters, and finds Tag in front of her. But when she found out Tag wasn't the father, she leaves the two alone. Ross is about to leave, when he spots the red sweater. He then claims that it's his, much to Monica and Phoebe's shock. He then leaves as Monica and Phoebe realize that he is the father of Rachel's baby. Joey, slow as ever, takes a minute to work this out, and is just as shocked as the others.",
        // The time rachel made trifle
        // Joey says I am not even sad
        // The fork-in-the-jacket moment. What are we having
        // Joey eating whole turkey
        // Joey stuck his head in Monica's Door
        // Joey is a sex-pervert (has naked pic of Monica)
        
    ];
}

// Method to the GenerateNewText constructor function that generates a paragraph
GenerateNewText.prototype.getParagraph = function () {
    let paragraph = this.sentences[Math.floor(Math.random() * this.sentences.length)];
    return paragraph;
};

// Method to the GenerateNewText constructor function that generates multiple paragraphs from paragraphs
GenerateNewText.prototype.getAllParagraphs = function (numberOfParagraphs) {
    let allParagraphs = [];

    while (allParagraphs.length < numberOfParagraphs) {
        allParagraphs.push(this.getParagraph());
    }

    // Convert array into HTML string
    let paragraphHTML = "";
    allParagraphs.forEach(function (paragraph) {
        paragraphHTML += "<p>" + paragraph + "</p>";
    });
    return paragraphHTML;
};

module.exports = loremIpsum;
